version: "3.5"

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    volumes:
      - ./script/script.sql:/docker-entrypoint-initdb.d/script.sql
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "300MB"

  api01: &api
    image: .
    hostname: api01
    environment:
      - HTTP_PORT=3332
      - TCP_PORT=3302
    depends_on:
     - db
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - HTTP_PORT=3333
      - TCP_PORT=3303

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  rinha-network: